version: 2

build:
  os: ubuntu-22.04
  tools:
    python:
      version: 3.13

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
