
services:
  aiohttp:
    env_file:
      - .docker.env
    build:
      context: .
      args:
        VOLUME_DIRNAMES: /mnt/data;/mnt/static

    environment:
      - AIOHTTP_PORT=8080
      - AIOHTTP_HOST=0.0.0.0
      - AIOHTTP_STATIC_ROOT=/mnt/static
      - S3_TMP_DIR=/mnt/data/s3-tmp
      - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws_credentials

    secrets:
      - aws_credentials

    volumes:
      - web_static:/mnt/static
      - data:/mnt/data


  frontend:
    build:
      context: ./frontend-service
      dockerfile_inline: |
        FROM nginx:1.21.6

        RUN mkdir -p /etc/nginx/templates
        RUN mkdir -p /mnt/data

        COPY proxy_params /etc/nginx/
        COPY templates/default.conf.template /etc/nginx/templates/default.conf.template

    environment:
      - NGINX_PORT=80
      - NGINX_SERVER_NAME=localhost
      - NGINX_ROOT=/var/www
      - DATA_ROOT=/mnt/data/data
      - AIOHTTP_STATIC_ROOT=/var/www/static
      - AIOHTTP_SERVER=aiohttp:8080

    volumes:
      - web_static:/var/www/static
      - data:/mnt/data

    ports:
      - "80:80"

volumes:
  data:
  web_static:


secrets:
  aws_credentials:
    file: ~/.aws/granicus-credentials
