
services:
  nextjs:
    build:
      context: ./webapp
      target: runner
      args:
        - CONTENT_HOST_PATH=http://frontend
    ports:
      - "3000:3000"
    links:
      - frontend
    hostname: nextjs
    environment:
      - CONTENT_HOST_PATH=http://frontend


  frontend:
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:1.21.6

        RUN mkdir -p /etc/nginx/templates
        RUN mkdir -p /mnt/data

        COPY webapp/.nginx/templates/default.conf.template /etc/nginx/templates/default.conf.template

    environment:
      - NGINX_PORT=80
      - NGINX_SERVER_NAME=localhost
      - NGINX_ROOT=/var/www
      - NEXTJS_SERVER=nextjs:3000

    volumes:
      - type: bind
        source: ./data
        target: /mnt/data/data
        read_only: true

    ports:
      - "80:80"
