[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "granicus-archiver"
version = "0.0.1"
dependencies = [
    "aiohttp",
    "aiojobs",
    "aiofile",
    "yarl",
    "pyyaml",
    "pyquery",
    "click",
    "loguru",
    "aiogoogle",
    "pypdf"
]

[project.optional-dependencies]
tests = ["pytest", "pytest-asyncio"]
docs = ["sphinx", "furo"]


[tool.setuptools.packages.find]
where = ["src"]


[tool.pytest.ini_options]
testpaths = [
    'tests',
    'src'
]
addopts = "--doctest-modules"
