[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "granicus_dump"
version = "0.0.1"
dependencies = [
    "aiohttp",
    "aiojobs",
    "aiofile",
    "yarl",
    "pyquery",
    "click",
    "loguru"
]

[tool.setuptools.packages.find]
where = ["src"]
