[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "granicus_dump"
version = "0.0.1"
dependencies = [
    "aiohttp",
    "aiojobs",
    "aiofile",
    "yarl",
    "pyquery",
    "click",
    "loguru"
]

[project.optional-dependencies]
tests = ["pytest", "pytest-asyncio"]


[tool.setuptools.packages.find]
where = ["src"]


[tool.pytest.ini_options]
testpaths = [
    'tests'
]
